=== Sunagatov/Iced-Latte/src/test/resources/model/product-list-pagination-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "products": {
      "type": "array",
      "items": {
        "$ref": "product-schema.json"
      }
    },
    "page": {
      "type": "integer"
    },
    "size": {
      "type": "integer"
    },
    "totalElements": {
      "type": "integer"
    },
    "totalPages": {
      "type": "integer"
    }
  },
  "required": [
    "products",
    "page",
    "size",
    "totalElements",
    "totalPages"
  ]
}

=== Sunagatov/Iced-Latte/src/test/resources/product/model/product-pagination-macchiato-model.json
{
  "products": [
    {
      "id": "46f97165-00a7-4b45-9e5c-09f8168b0047",
      "name": "Macchiato",
      "description": "Espresso with a Dash of Frothy Milk",
      "price": 3.99,
      "quantity": 90,
      "active": true
    }
  ],
  "page": 1,
  "size": 1,
  "totalElements": 6,
  "totalPages": 6
}

=== Sunagatov/Iced-Latte/src/test/resources/product/model/product-pagination-americano-model.json
{
  "products": [
    {
      "id": "e6a4d7f2-d40e-4e5f-93b8-5d56ce6724c5",
      "name": "Americano",
      "description": "Espresso Diluted with Hot Water",
      "price": 4.49,
      "quantity": 70,
      "active": true
    }
  ],
  "page": 5,
  "size": 1,
  "totalElements": 6,
  "totalPages": 6
}
